GET http://localhost:3000/studies/c3411728-6d54-485a-b46d-da0f212c567e/habit

###
POST http://localhost:3000/studies/c3411728-6d54-485a-b46d-da0f212c567e/habit
Content-Type: application/json

{
  "name" : "근력운동 30분"
}

###
PATCH http://localhost:3000/habits/fa52ee55-f92a-437e-b189-2c6ecf163a8e
Content-Type: application/json

{
  "isCompleted" : true
}

###
DELETE http://localhost:3000/habits/ed42e270-a240-4fca-97c7-89a690e2343a