GET http://localhost:3000/studies?limit=10

###

GET http://localhost:3000/studies/c3411728-6d54-485a-b46d-da0f212c567e

###

POST http://localhost:3000/studies
Content-Type: application/json

{
  "nickName" : "study8",
  "password" : "study8",
  "name" : "릴스 그만보기",
  "description" : "도파민 중독에서 벗어나자",
  "background" : "green"
}


###
PATCH http://localhost:3000/studies/bd5c1b4a-575b-4940-9f99-0fcaa7bb97f1
Content-Type: application/json

{
  "password" : "study1"
}

###
DELETE http://localhost:3000/studies/82480c2e-d811-4a85-8396-ad8c3ea08602