GET http://localhost:3000/studies?limit=11

###

GET http://localhost:3000/studies/19a98806-69b4-4064-a7e5-1ca63ef29e30

###

POST http://localhost:3000/studies
Content-Type: application/json

{
  "nickName" : "육쌈",
  "password" : "watch666",
  "name" : "미라클모닝",
  "description" : "6시에 일어나는 나라의 어른이 되어보자",
  "background" : "image_4"
}


###
PATCH http://localhost:3000/studies/19a98806-69b4-4064-a7e5-1ca63ef29e30
Content-Type: application/json

{
  "name" : "QA 프로젝트 하기"
}

###
DELETE http://localhost:3000/studies/19a98806-69b4-4064-a7e5-1ca63ef29e30