GET http://localhost:3000/studies?limit=11

###

GET http://localhost:3000/studies/e79e5813-a84b-45ae-b732-73704e58a933

###

POST http://localhost:3000/studies
Content-Type: application/json

{
  "nickName" : "고고싱",
  "password" : "gogo99",
  "name" : "카페가기",
  "description" : "일주일에 두번은 외출을 하자",
  "background" : "image_4"
}


###
PATCH http://localhost:3000/studies/17d796c1-5077-4078-871b-62e90accef4d
Content-Type: application/json

{
  "name" : "카페 가기"
}

###
DELETE http://localhost:3000/studies/19a98806-69b4-4064-a7e5-1ca63ef29e30